services:
  backapp:
    image: backapp:latest

  frontapp:
    image: frontapp:latest  
    ports:
    - 8083:8083
    depends_on:
      - backapp
    environment:
      - BACK_URL=http://backapp:8082      
